version: '3.7'

services:
    redis:
        image: redis:6.2-rc-alpine
        ports:
            - 6379:6379
    postgres:
        image: postgres:14
        ports:
            - 5432:5432
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: twitter
